system:
    device: cpu

data:
    dataset_path: dataset/
    batch_size: 64

model:
    input_dim: 784
    output_dim: 10
    hidden_dims: [200]
    learning_rate: 1e-3
    weight_decay: 1e-6

trainer:
    epochs: 5
    log_interval: 10
