hydra:
  job_logging:
    root:
      level: INFO

system:
  device: cpu

data:
  dataset_path: dataset/
  batch_size: 64

model:
  checkpoint_path: model/model.pth
  load_from_checkpoint: false
  network:
    input_dim: 784
    output_dim: 10
    hidden_dims: [200]
  optimizer:
    learning_rate: 1e-3
    weight_decay: 1e-6
  scheduler:
    factor: 0.1
    patience: 3

trainer:
  epochs: 5
  grad_accum_steps: 2
  log_interval: 200
