site_name: Canvas
site_url: https://ramanakshay.github.io/canvas-template/
repo_url: https://github.com/ramanakshay/canvas-template
edit_uri: edit/main/docs/
nav:
  - Home: index.md

theme:
  name: material
  favicon: images/canvas_logo.svg
  logo: images/canvas_logo.svg
  features:
    - navigation.instant
    - toc.integrate
  palette:
    - primary: white

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
      text: Roboto
      code: Roboto Mono
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - toc:
      toc_depth: 2
