[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "canvas"

[project]
name = "canvas-template"
readme = "README.md"
version = "0.1.3"
description = "A flexible and modular deep learning project template."
authors = [{ name = "Akshay Raman", email = "ar8692@nyu.edu" }]
license = "MIT"
license-files = ["LICEN[CS]E*"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
requires-python = ">=3.9"
dependencies = ["cookiecutter", "click"]

[project.scripts]
canvas = "canvas.__main__:main"

[project.urls]
"Homepage" = "https://github.com/ramanakshay/canvas/"
"Source Code" = "https://github.com/ramanakshay/canvas/"
