system:
  device: auto

data:
  dataset_path: data/dataset/
  batch_size: 64

model:
  input_dim: 784
  hidden_dim: 200
  output_dim: 10

algorithm:
  epochs: 5
  learning_rate: 1e-3
  weight_decay: 1e-6
